version: '3'

networks:
  custom-net:
    driver: bridge
    ipam:
      config:
        - subnet: 1.0.0.0/24

services:
  app:
    build:
      context: .
      dockerfile: ./src/Docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      custom-net:
        ipv4_address: 1.0.0.2
    depends_on:
      - mongodb
    restart: always
    command: npm run start:dev

  mongodb:
    image: mongo:3.6
    restart: always
    networks:
      custom-net:
        ipv4_address: 1.0.0.3 

